print("Welcome to the best RPG Ever! Before we begin, we need to start out with the basic necessities")
username = input("What would you like your username to be?")
print(f"Cool name {username}!")
print("Now we need to choose your role")
choice = input(f"Please choose either role: Hero or Prince")
print("Great!")
print(f"Now that we have the necessities out of they way. It is time to begin {username}")
